name: marketplace-stack
version: '3.8'
services:
  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
      - "29092:29092"
    networks:
      - marketplace-network
    environment:
      KAFKA_KRAFT_MODE: "true"
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093" #cluster mekanizması yönetimi
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL_PLAINTEXT://:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL_PLAINTEXT://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL_PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CLUSTER_ID: "Mk3OEYBSD34fcwNTJENDM2Qk"
    volumes:
      - kafka_data:/var/lib/kafka/data

  kafbat-ui:
    container_name: kafbat-ui
    image: ghcr.io/kafbat/kafka-ui
    ports:
      - 8092:8080
    depends_on:
      - kafka
    networks:
      - marketplace-network
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_NAME: marketplace
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.2
    container_name: elasticsearch
    environment:
      - node.name=es-node
      - cluster.name=es-cluster
      - discovery.type=single-node
      - xpack.security.enabled=false  # Güvenlik kapalı
      - xpack.license.self_generated.type=basic
      - network.host=0.0.0.0  # Dış erişime izin ver
      - http.port=9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - marketplace-network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "curl -s http://localhost:9200/_cluster/health?wait_for_status=yellow || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 20 # 20 kez tekrarla
      start_period: 30s

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.2
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - marketplace-network
    restart: unless-stopped

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - marketplace-network
    volumes:
      - mysql_data:/var/lib/mysql

  marketplace-elastic:
    build:
      context: ./submodules/elastic
    ports:
      - "8082:8082"
    networks:
      - marketplace-network
    depends_on:
      elasticsearch:
        condition: service_healthy #elasticsearch'in sağlıklı olmasını bekler
      kafka:
        condition: service_started
    environment:
      SPRING_ELASTICSEARCH_URIS: http://elasticsearch:9200
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  marketplace-core:
    build:
      context: ./submodules/core
    ports:
      - "8081:8081"
    networks:
      - marketplace-network
    depends_on:
      - mysql
      - kafka
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/marketplace?createDatabaseIfNotExist=true

  marketplace-customer:
    build:
      context: ./submodules/customer
    ports:
      - "8080:8080"
    networks:
      - marketplace-network
    depends_on:
      - marketplace-elastic
      - marketplace-core
    environment:
      APP_ELASTIC_URL: http://marketplace-elastic:8082
      APP_CORE_URL: http://marketplace-core:8081

volumes:
  kafka_data:
  esdata:
    driver: local
  mysql_data:

networks:
  marketplace-network:
    name: marketplace-network
    driver: bridge

